// <auto-generated />
using System;
using ChefAI.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChefAI.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818130217_TranslateDietaryRestrictions")]
    partial class TranslateDietaryRestrictions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChefAI.Domain.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ConditionValue")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("badges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = "TotalRecipes",
                            ConditionValue = 1,
                            Description = "Generá tu primera receta",
                            IconUrl = "",
                            Name = "Primera receta"
                        },
                        new
                        {
                            Id = 2,
                            Condition = "TotalRecipes",
                            ConditionValue = 10,
                            Description = "Generá 10 recetas",
                            IconUrl = "",
                            Name = "Cocinero curioso"
                        },
                        new
                        {
                            Id = 3,
                            Condition = "TotalRecipes",
                            ConditionValue = 50,
                            Description = "Generá 50 recetas",
                            IconUrl = "",
                            Name = "Chef prolífico"
                        },
                        new
                        {
                            Id = 4,
                            Condition = "CurrentStreak",
                            ConditionValue = 7,
                            Description = "Mantené una racha de 7 días",
                            IconUrl = "",
                            Name = "Racha de fuego"
                        },
                        new
                        {
                            Id = 5,
                            Condition = "TotalFavorites",
                            ConditionValue = 5,
                            Description = "Marcá 5 recetas como favoritas",
                            IconUrl = "",
                            Name = "Coleccionista"
                        },
                        new
                        {
                            Id = 6,
                            Condition = "HasParticipatedInChallenge",
                            Description = "Participá en tu primer desafío",
                            IconUrl = "",
                            Name = "Primer desafío"
                        },
                        new
                        {
                            Id = 7,
                            Condition = "TotalVotesReceived",
                            ConditionValue = 10,
                            Description = "Recibí 10 votos en desafíos",
                            IconUrl = "",
                            Name = "Popular"
                        },
                        new
                        {
                            Id = 8,
                            Condition = "HasUsedPhotoDetection",
                            Description = "Usá la detección por foto",
                            IconUrl = "",
                            Name = "Explorador"
                        });
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StarIngredientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StarIngredientId");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.ChallengeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("challenge_entries", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.DietaryRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("dietary_restrictions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sin carne ni pescado, pero puede incluir lácteos y huevos.",
                            Name = "Vegetariano"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sin productos de origen animal, incluidos lácteos y huevos.",
                            Name = "Vegano"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sin cereales que contengan gluten como trigo, cebada y centeno.",
                            Name = "Sin Gluten"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sin productos lácteos.",
                            Name = "Sin Lácteos"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sin frutos secos ni productos que los contengan.",
                            Name = "Sin Frutos Secos"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sin carne, pero incluye pescado y mariscos.",
                            Name = "Pescetariano"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dieta baja en carbohidratos y alta en grasas, enfocada en carnes, pescado, huevos, lácteos, frutos secos y vegetales bajos en carbohidratos.",
                            Name = "Keto"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Excluye cerdo y productos derivados.",
                            Name = "Sin Cerdo"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Limita la ingesta de carbohidratos, centrándose en proteínas y grasas.",
                            Name = "Bajo en Carbohidratos"
                        });
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HasAwardedFavoritePoints")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTimeOffset?>("TokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.UserBadge", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("user_badges", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.UserPoints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_points", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultServings")
                        .HasColumnType("integer");

                    b.Property<bool>("HasUsedPhotoDetection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("MaxCookingTime")
                        .HasColumnType("interval");

                    b.Property<string>("PreferredDifficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeEntryId");

                    b.HasIndex("UserId", "ChallengeEntryId")
                        .IsUnique();

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("DietaryRestrictionRecipe", b =>
                {
                    b.Property<int>("DietaryRestrictionsId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipesId")
                        .HasColumnType("integer");

                    b.HasKey("DietaryRestrictionsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("recipe_dietary_restriction", (string)null);
                });

            modelBuilder.Entity("DietaryRestrictionUserProfile", b =>
                {
                    b.Property<int>("DietaryRestrictionsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfilesId")
                        .HasColumnType("integer");

                    b.HasKey("DietaryRestrictionsId", "UserProfilesId");

                    b.HasIndex("UserProfilesId");

                    b.ToTable("user_profile_dietary_restriction", (string)null);
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.RecipeIngredient", "StarIngredient")
                        .WithMany()
                        .HasForeignKey("StarIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StarIngredient");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.ChallengeEntry", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Entries")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefAI.Domain.Entities.Recipe", "Recipe")
                        .WithMany("ChallengeEntries")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefAI.Domain.Entities.User", "User")
                        .WithMany("ChallengeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefAI.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.UserPoints", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.User", "User")
                        .WithOne("UserPoints")
                        .HasForeignKey("ChefAI.Domain.Entities.UserPoints", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("ChefAI.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Vote", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.ChallengeEntry", "ChallengeEntry")
                        .WithMany("Votes")
                        .HasForeignKey("ChallengeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefAI.Domain.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengeEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietaryRestrictionRecipe", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.DietaryRestriction", null)
                        .WithMany()
                        .HasForeignKey("DietaryRestrictionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefAI.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietaryRestrictionUserProfile", b =>
                {
                    b.HasOne("ChefAI.Domain.Entities.DietaryRestriction", null)
                        .WithMany()
                        .HasForeignKey("DietaryRestrictionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefAI.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.ChallengeEntry", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("ChallengeEntries");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("ChefAI.Domain.Entities.User", b =>
                {
                    b.Navigation("ChallengeEntries");

                    b.Navigation("Recipes");

                    b.Navigation("UserBadges");

                    b.Navigation("UserPoints")
                        .IsRequired();

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
